apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cG9zdGdyZXMxMjM=  # postgres123 (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
data:
  password: ""  # empty password for default user (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=  # your-jwt-secret-change-this-in-production (base64 encoded)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  CORS_ORIGIN: "*"
  LOG_LEVEL: "info"
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "lugx_gaming"
  # ClickHouse configuration
  CLICKHOUSE_URL: "http://clickhouse-service:8123"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_DATABASE: "analytics"
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  # JWT configuration
  JWT_EXPIRES_IN: "7d"
