apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "development"
  DB_HOST: "iit-test-dev-db.cv0gc48uo7w1.ap-southeast-1.rds.amazonaws.com"
  DB_NAME: "lugx_gaming_dev"
  DB_PORT: "5432"
  CLICKHOUSE_HOST: "clickhouse-service"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DATABASE: "analytics_dev"
  CLICKHOUSE_USERNAME: "default"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
stringData:
  DB_USER: "dbadmin"
  DB_PASSWORD: "LionKing1234"
  CLICKHOUSE_PASSWORD: "dev_clickhouse_password"
  JWT_SECRET: "dev-jwt-secret-for-testing"
