apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
stringData:
  DB_USER: "dbadmin"
  DB_PASSWORD: "LionKing1234"
  CLICKHOUSE_PASSWORD: "dev_clickhouse_password"
  JWT_SECRET: "dev-jwt-secret-for-testing"
