apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
stringData:
  DB_USER: "iit_admin"
  DB_PASSWORD: "SevenEleven12"
  CLICKHOUSE_PASSWORD: "dev_clickhouse_password"
  JWT_SECRET: "dev-jwt-secret-for-testing"
